package ru.chernov.algthms.hashmap.eazy;

/**
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 */
public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        int[] lt = new int[26];
        for (int i = 0; i < t.length(); i++) {
            lt[t.charAt(i) - 'a'] += 1;
            if (i != s.length()) {
                lt[s.charAt(i) - 'a'] -= 1;
            }
        }

        for (int i = 0; i < lt.length; i++) {
            if (lt[i] == 1) {
                return (char)(i + 'a');
            }
        }

        return '0';
    }
}
